set dotenv-load := true


terraform-init:
    terraform init

terraform-plan:
    terraform plan

terraform-apply *FLAGS:
    terraform apply {{ FLAGS }}

terraform-destroy:
    terraform destroy

terraform-format:
	terraform fmt

terraform-validate:
	terraform validate

terraform-output:
	terraform output

terraform-console:
	terraform console

get-caller:
    aws sts get-caller-identity
